### ISSUE TITLE
Crash sign out sign in back

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#109]
Sounds like this is an instance of #414.

5.7 (2) TestFlight

Signed in already

Signed out (to see the screens without Twitter Facebook)

Tapped already have account

Then tapped back 

And crash

Sentry: BEESWIFT-JY

**Comment by krugerk** [comment]
did not see the same on the simulator though

**Comment by andrewpbrett** [comment]
Are you able to reproduce this on your device still?

**Comment by krugerk** [comment]
had seen it twice using the steps above before creating the ticket.

could test/check it again

had hoped for some insight thanks to the stacktrace / crash report (#111 )

**Comment by krugerk** [comment]
Yes
Happened just now again 


Signed into app
Using 5.7 (2) from TestFlight

Gallery / settings / sign out

Then at sign in / sign up screen
Tapped already have an account
At that next screen, sign in, tapped back button

App crashed

**Comment by andrewpbrett** [comment]
I'm not seeing the same unfortunately, either on the device or on the simulator. I have reinstalled the sentry build script and it's uploaded the symbols. I think you might need to cause the crash again for a new symbolicated crash report.

**Comment by andrewpbrett** [comment]
Actually I think I did just reproduce it; it wasn't a specific button press, though. After I signed out a background update caused an Apple Health sync and the app tried to send a datapoint to beeminder, but I wasn't logged in, which caused a crash ("Unexpectedly found nil while unwrapping an Optional value").

**Comment by krugerk** [comment]
Makes sense.
It was my guess too that it was one of the force unwraps.

So when signing out, cancel out the HealthKit pending queries?

**Comment by krugerk** [comment]
Obviously we could go through the code, replacing all of the force unwraps concerning username, or even just all of them (similar to #140) and that might prevent this crash.

It seems though we might want to 'rewind' changes made when setting up healthkit integration when signing out.

 - disabling background updates on signout: https://developer.apple.com/documentation/healthkit/hkhealthstore/1614158-disableallbackgrounddelivery 
 - or better yet, stopping long running queries: https://developer.apple.com/documentation/healthkit/hkhealthstore/1614173-stop

**Comment by andrewpbrett** [comment]
Both of those sound great to me! (getting rid of all force unwraps and stopping queries on signout).
