### ISSUE TITLE
App URL (beeminder://...) for app actions like adding a +1 to a goal

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#115]
```[tasklist]
### Desiderata
- [ ] Clarify if this is subsumed by #71 
- [ ] Coordinate with Beedroid so both apps respond to the same URL the same way
- [ ] TBD -- other actions besides opening a goal page?
```

The iOS app currently supports URLs starting with "beeminder://" that will cause the app to open and take some action inside the app. One cool thing that that allows is making, say, a QR code to add a +1 to a goal.

Here's one -- beeminder://?slug=steps -- that should open a goal with goalname "steps" in the iOS app:

!["beeminder://?slug=steps"](https://user-images.githubusercontent.com/4656811/89080151-5ac38f00-d388-11ea-86c2-9583bac23830.png)

## Cognata

* #71

_**Verbata**: QR codes, app shortcuts, special URLs for taking special actions,_

**Comment by krugerk** [comment]
would make sense for the two native apps to support the same url schemes.

**Comment by andrewpbrett** [comment]
cc @adamwolf

**Comment by krugerk** [comment]
This ticket is perhaps a specific use case enabled by creating the in-app URLs needed anyway for #71.

**Comment by dreeves** [comment]
User feedback:

> After setting up Beeminder two weeks ago I am playing around with Apple shortcuts 😉
> 
> Is there a way I can have a link open in the app instead of the website? For example, beeminder.com/jka/running will open in Safari on my iPhone and show "open in app" on top. When I click open it takes me to the apps Goals overview instead of the running goal directly. From other apps I know there are app links which could potentially do what I am looking for.

**Comment by theospears** [comment]
I think that feature request is different from this issue. This issue is about app urls for actions, whereas I think the user feedback is about [universal links](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content?language=objc).

**Comment by theospears** [comment]
I believe shortcuts are a better way to do this than app urls.
