### ISSUE TITLE
Views in Today Widget can be misaligned

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#151]
```[tasklist]
### Desiderata
- [ ] Confirm this replicates in modern BeemiOS
```

This was noticed in the simulator and on a device running iOS 13.6 using version 5.7 (4) of the app. As seen in the screenshot, some of the text overlaps the the add-data entry area. This perhaps is a recent bug since only recently the today widget displays more than one goal (#92).

A guess is that this is a cell re-use bug because the position of the text in the second and third cells is the same as in the first - centered vertically. That is OK in the first because it is an auto goal and thus does not display the add data view elements.

![overlapping views in today widget](https://user-images.githubusercontent.com/4656811/90791015-023d3d00-e309-11ea-86d9-e7fc6647af16.png)

## Cognata

* #3  

_**Verbata**: css, alignment, layout, visual bugs,_

**Comment by dreeves** [comment]
Nice catch! Is it a regression? I'm tentatively adding the tag for that (ZOM) just in case, which you can remove if it's not.

**Comment by krugerk** [comment]
As long as I have been using the beeminder for ios app, the today widget has only ever shown 1 goal (although the code elsewhere made it seem up to three should be shown). So it became visible/an issue after #92, which shows up to three goals.

**Comment by dreeves** [comment]
Roger that! Still an embarrassing bug but I shall remove the zombie tag!

**Comment by krugerk** [comment]
Actually the text was aligned properly. What was wrong though were the data entry views. In the screenshot attached to this ticket, the data entry views should not have appeared on any of the three goals displayed - all are autodata goals.

**Comment by theospears** [comment]
Today widget is deprecated, no more development will be done on it
