### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#155]
```[tasklist]
### Desiderata
- [ ] Theo opines on how valuable this would be
```

When running `fastlane release` it should 1) ensure we're on the `master` branch and 2) automatically tag HEAD with the release number.

_**Verbata**: deploys, deploying, deployments, dev env, releases,_

**Comment by theospears** [comment]
I'm going to say `increment_minor_version` and `increment_major_version` are close enough to this.
