### ISSUE TITLE
iOS Apple Health Integration Bug: Inflated Totals Because of Redundant Data from Multiple Sources (Possibly Unavoidable?)

### ISSUE THREAD

**Issue by chipmanaged** [beeminder/BeeSwift#16]
@apb There might be an issue with the numbers fetched from Apple Health, and I don't know of a way around it at the moment.

Beeminder iOS has, I suspect no way of ignoring the data sources that Apple Health has deprioritized (i.e. ignoring) in favour of using a higher priority source that recorded data at the same time instead (the watch's data vs. a 3rd party app, for instance).

So, if a workout is added from a 3rd party app, in order to avoid duplicate calorie counting, the Apple Health active energy summary counts only the Apple watch's data and not the 3rd party app's input. The priorities can be changed so that different apps take precedence, ignoring the others as duplicates, but the problem remains the same: Apple Health's summaries eliminate duplicate data, and Beeminder iOS sums all of the input received from *every* data source, rather than fetching just the summary/total numbers from Apple Health's "Today" tab, which have tossed out duplicate data. (I don't know whether it's possible to do that, but I suspect not.) 

As a result, the Beeminder iOS data is inflated because of duplicate data coming from multiple sources, and the historical data won't match Apple Health's historical data. I have no solution in mind, I'm afraid. The Workflow app (http://workflow.is) has the same problem. That's how I found it and was prompted to check whether Beeminder iOS was being hit by the same issue.

**Comment by andrewpbrett** [comment]
I'm going to close this as "it's as close as we're going to get"
