### ISSUE TITLE
Facilitate testing with build info

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#169]
As is, the app can be build from source, installed from the App Store, and/or installed from TestFlight.

Let us assume one building from source know which 'version' he/she is using. For those distributed builds however, it would be beneficial to be able to quickly, uniquely identify a given installation such that it is known which changes/commits should be present in that build.

The version string (e.g. 5.7) need not convey all of the data. Instead build info could be displayed, perhaps by tapping the version? 
Build date
Build job
Corresponding git commit

(It was noticed during the recent 5.7 release - an older Tesflight build showed 5.7 in the app in Settings but was not of course what would later become the App Store release 5.7.)

**Comment by krugerk** [comment]
Settings screen in the app shows version name and build number as of #225.

**Comment by andrewpbrett** [comment]
I think this is closed as of #225?

**Comment by krugerk** [comment]
So far there is not enough data visible in the app to uniquely correlate to the build environment.
Some other handy data:
- build date
- build machine
- git commit id 
- branch name
- environment (currently just one)
- build job id
