### ISSUE TITLE
Built-in timer doesn't respect Beeminder definition of end-of-day

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#17]
User reports submitting a timer at 2 minutes after a 13:00 deadline. The actual calendar day is the 26th, user expects datapoint with date of the 27th, since that's how Beeminder deadlines behave, but gets a datapoint with date of the 26th.

(I checked the server logs and confirmed that the Add Datapoint request was received at 2 minutes after the deadline, and the datapoint was submitted with `urtext: 26 <value> <comment>`.)

## Cognata

* #35 
* #450
* https://doc.beeminder.com/midnight (in particular the appendix rationalizing this design choice)

_**Verbata**: timer mode, beeminder day vs calendar day, end-of-day definition, deadline as end-of-day,_

**Comment by andrewpbrett** [comment]
Report:

>Basically, if you have a goal with a deadline after midnight and you add some data with the built in timer at, say, 1 AM the iOS app will add it as the calendar day. It happened to me just now (deadline at 2 AM, doing some late night reading at 1 AM) and I got pretty confused because it didn't update the due date (as the data was added as if it was the next day). I hope that's enough data for you to replicate it!
