### ISSUE TITLE
Better dark mode?

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#176]
```[tasklist]
### Desiderata
- [ ] Screenshots of the status quo
- [ ] Discuss how much we care? Does user-theo care?
```

## Cognata

* #94
* #95 
* #150 
* #346 
* https://forum.beeminder.com/t/nailing-down-the-changelog-for-beemios-version-5-7/7155/16

_**Verbata**: dark mode vs light mode,_

**Comment by theospears** [comment]
I'm going to close out this as too general to be actionable. People should feel free to open issues for specific improvements.
