### ISSUE TITLE
Is the app deleting datapoints (rather than update?) causing clobbers/derails

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#18]
It looks like this is happening with apple health updates: We have job A updates 2/25 by deleting and re-adding a datapoint at the same time that job B updates 2/26 in the same way, so that A sees missing data on the 26th when it tries to update the graph and job B sees missing data on the 25th when it tries to update the graph?

can the app batch its own updates? do we need an api endpoint that edits datapints rather than deleting and re-adding them? (do we already have one?)

**Comment by krugerk** [comment]
Given the data, declaring 'could not reproduce'.

Feel free to report / reopen with a recent app version. Screenshots of the goal in the app and on the website as well as those from Apple Health could be helpful.
Also, do note the metric (steps, sleep, etc) being tracked.
