### ISSUE TITLE
Make deadline visible

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#185]
Some goals have deadlines and it may be desirable to see those. 

At least one User of the android app requested the feature.

https://github.com/beeminder/beedroid/issues/112

**Comment by adamwolf** [comment]
Do you already show the "safesum"?  That will show the deadline on emergency days.

**Comment by krugerk** [comment]
Ah sorry. I mistook this as showing a goal about to finish.

Yeah we already show safesum, something like "+1 due in 5d 23h 14m or pay $"
