### ISSUE TITLE
memory leak or something? "app is super slow. normal again after i force quit"

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#19]
quoting the user

> I just experimented.
>- pulling down from the main list (app start-up page) to update - I waited 70 seconds with the spinning update icon before giving up. (This is fairly normal for me of late - sometimes it does update but more often not.) 
>- tapping into a specific commitment, adding data, submitting - took 9 secs but did get there eventually. 
>- force-closing the app & restarting - connects & updates nearly immediately (couple of seconds). 
>
>I’m on iOS 12.14 and this was on Wifi (but I haven’t noticed 4G being quicker).

**Comment by krugerk** [comment]
I have not seen this at all and would so it might no longer be relevant with [App Version 5.6.4](https://github.com/beeminder/BeeSwift/releases/tag/5.6.4).

Could we ask for more data?
 - Number of goals
 - iOS Device
 - App Version

**Comment by krugerk** [comment]
an old issue that has not (yet) been reproduced with recent versions of the app (5.6.4)
