### ISSUE TITLE
Settings icons overlap

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#192]
# Defectus Demonstrandum

## Reseminata 

1. Open Settings screen

## Expectata

Each row should have its own icon.

## Resultata

The icons overlap with each other.
![IMG_2558](https://user-images.githubusercontent.com/35588/92500268-ca137680-f1b1-11ea-9b34-9096af30af42.jpg)

# Veni Vidi Vici

["I came, I saw, I conquered", i.e., the report on how it was resolved]

**Comment by krugerk** [comment]
In SettingsTableViewCell, an ImageView is added as a subview of the cell's contentView as long as imageName is not nil. If imageName is set to nil, the previously set imageView is not removed from the contentView.
Thus, prepareForReuse does not reset the cell completely for reuse.

**Comment by krugerk** [comment]
This may have been fixed in Commit 7a76bdd3c13ee37dd0c957a57f56c0c736b8742f as part of #167.
