### ISSUE TITLE
Doing a GET on a goal sends the access_token twice

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#198]
```[tasklist]
### Desiderata
- [ ] Replicate it in current version (6.6)
- [ ] Characterize the severity
```

1. Tap a goal in the gallery to enter the goalVC.
2. Upon `viewDidAppear`, `refreshGoal` will be called which in turn makes a GET request to obtain the goal.
3. It appears the access_token is attached twice to this request:
`https://www.beeminder.com//api/v1/users/<user>/goals/<goalslug>?access_token=<access_token>&datapoints_count=5&access_token=<access_token>`

The access token is appended to the URL directly and RequestManager checks the parameters for the access token but does not check the rest of the URL. Instead it should follow the others, either passing the access token along in the parameters or allowing the default behavior to append the necessary token. 

## Cognata

* https://github.com/beeminder/BeeSwift/blob/d79461c2c685db215d75056d355ba6d6b2dc4fce/BeeSwift/GoalViewController.swift#L573
* https://github.com/beeminder/BeeSwift/blob/d79461c2c685db215d75056d355ba6d6b2dc4fce/BeeSwift/RequestManager.swift#L77

_**Verbata**: tidiness, inconsistencies, redundant parameters,_

**Comment by krugerk** [comment]
I noticed a few other inconsistencies as well. Most calls to RequestManager leave the access_token parameter out, expecting RequestManager to fill it if missing. However some places create the parameters dictionary with or just for the access token. 

in EditDatapointVC:
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/EditDatapointViewController.swift#L191
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/EditDatapointViewController.swift#L207

in TodayTableViewCell:
- https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwiftToday/TodayTableViewCell.swift#L154
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwiftToday/TodayTableViewCell.swift#L174

and in JSONGoal:
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/JSONGoal.swift#L636
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/JSONGoal.swift#L659
 - https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/JSONGoal.swift#L667

**Comment by theospears** [comment]
The app no longer sends the access token as a url parameter at all (except when opening the goal webview)

**Comment by krugerk** [comment]
Switch to auth header over url parameter was made in https://github.com/beeminder/BeeSwift/pull/447.
