### ISSUE TITLE
Suggestions from apolyton

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#2]
Data points on the app seems that they are often stale (not updated) or even wrong. See screenshot just now from my forest goal vs the actual data on the site:

![image](https://user-images.githubusercontent.com/9928/36927767-c6cbbfbc-1e34-11e8-9bf4-7f5e2040715a.png)

Also a couple suggestions I’ve been meaning to write

1. in the app, only show the first 3 decimal digits of data points. There is no use case for more
2. auto descriptions can be shortened so that they are more readable (see screenshot above, I can’t tell the source of the automation because the description is too long)
How about
“Automatically updated via” = “Auto update:”
“Automatically entered from” = “Auto entry:”

**Comment by andrewpbrett** [comment]
Staleness should be addressed as of 5.3; for the more concise display of datapoints, the app is using the "canonical" representation of the datapoint that the server is reporting. I'm going to close it in BeeSwift and see if @dreeves thinks it's worth it to change on the server side.
