### ISSUE TITLE
Goals intermittently disappearing from the app

### ISSUE THREAD

**Issue by chipmanaged** [beeminder/BeeSwift#20]
Nick Winter has suggested that this _might_ be happening to goals that weren't recently restarted, but he's not sure. I've only noticed it with restarted/unarchived goals myself, though.

**Comment by andrewpbrett** [comment]
From Nick: 

> I just realized a new goal I just created also frequently doesn't show up in the list, so it's unlikely to be something like "all archived and restarted goals before/after date X" or something like that.

Changing the title.
