### ISSUE TITLE
Use consistent color scheme based on safety buffer (safebuf)

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#206]
[Probably make a new gissue pointing to https://github.com/beeminder/beeminder/issues/1755]

BeemiOS currently does not place its own dots. However, it does use different colors based on safety buffer.

See https://github.com/beeminder/road/issues/111

```
color = (safebuf < 1 ? "#ff0000" :  # Red for beemergencies
         safebuf < 2 ? "#ffa500" :  # Orange for 1 safe day
         safebuf < 3 ? "#3f3fff" :  # Blue for 2 safe days
         safebuf < 7 ? "#00aa00" :  # Green for 3+ safe days
                       "#228B22")   # Forest green Grayson dots for 7+ safe days
```

Here is the app using red, orange, blue, and green (and possibly gray) for the color of the countdown:
https://github.com/beeminder/BeeSwift/blob/31bfceaeaa126adc9290b45afb17fc08832c8279/BeeSwift/JSONGoal.swift#L170-L182

And here the app uses green, blue, and orange as its delta colors:
https://github.com/beeminder/BeeSwift/blob/31bfceaeaa126adc9290b45afb17fc08832c8279/BeeSwift/JSONGoal.swift#L279-L291

## Cognata

* #55

_**Verbata**: red, orange, blue, green, dot colors, color scheme,_

**Comment by krugerk** [comment]
Keep #55 in mind

**Comment by dreeves** [comment]
Ah, interesting. But I'm confused about what needs to change on the BeemiOS / Swift side. Where do things like `UIColor.red` come from?

**Comment by krugerk** [comment]
[UIColor](https://developer.apple.com/documentation/uikit/uicolor) comes from Apple's UIKit. Red and a bunch of other standard colors have already been defined. The app does not show its own dots, just the graph it downloads. However, it does use color based on safety buffer for the amounts due ("+5" in blue, "+15" in green) and for a textual representation of the safety buffer ("Safe for 3 days")

**Comment by dreeves** [comment]
Got it. So this change can't be effected server-side, right? We need BeemiOS to implement the above function mapping number of safe days (`safebuf` in the API) to the actual color hex code?

**Comment by krugerk** [comment]
Correct. Originally I posted that the app obtains colors from the backend. Not true. It just uses safety buffer, part of a goal, provided by the backend, to determine colors.

**Comment by krugerk** [comment]
![image](https://user-images.githubusercontent.com/4656811/94550106-801f2d00-0253-11eb-8c45-acb13536d9e4.png)

**Comment by dreeves** [comment]
UPDATE: New decision is that BeemiOS should not do the mapping from `safebuf` to `color` by itself. Rather, the API will soon include a `color` attribute on the Goal object and BeemiOS should just use that.
