### ISSUE TITLE
Apple Health UX

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#210]
```[tasklist]
### Desiderata
- [ ] TBD
```

Great feedback from Alex Strick van Linschoten:

> I wish Beeminder's interaction with Apple Health was a little less finicky / hacky (maybe via some preset options for 'commonly-tracked things'). At the moment when adding an Apple Health data source, it's sometimes a little opaque exactly what units we're dealing with, what my goal numbers should be etc etc. And since you have to define all this ahead of time (before adding in the data source), it can mean multiple attempts at creating and then deleting goals.

_**Verbata**: apple health, user feedback,_

**Comment by krugerk** [comment]
agreed. Some of that is what I meant should be included in the documentation from #75 (not just the list of metrics but units, frequencies, and so on.)

re: 'having to define all this ahead of time' 
-> there should be a ticket for the backend to improve the create goal page such that one can select Apple Health and select a metric from the website.

**Comment by theospears** [comment]
I think the Apple Health preview screen addresses some of the issues here. Beyond that I'm not sure there's more that is actionable, so going to close this out. Feel free to re-open or file more issues with increased detail.
