### ISSUE TITLE
The goal list should show the delta for today for each goal

### ISSUE THREAD

**Issue by theospears** [beeminder/BeeSwift#211]
As a user, I use beeminder to keep track of various actions I intend to do daily, for example flossing.

For goals where I am on the verge of failing it is easy to see when I have done the action. However, for goals where I have a safety buffer the app does not make it easy to see whether or not I have yet done that action today. (Even if I have a safety buffer I still want to do it today, but not so badly that I set my max buffer to one day). This applies both to checking if I have done the action, or if I know I have done it checking if I updated beeminder. 

One solution to this would be for the list screen to also show any delta for the current day for each goal. So eg if I had flossed today it would show “+1 today”.

**Comment by krugerk** [comment]
@theospears 
The website displays a checkmark next to goals indicating data has been entered for that goal today. How would displaying such help you in your case? 
How about being able to filter accordingly (hide goals with data today, aka show only goals without a datapoint for today)?

**Comment by krugerk** [comment]
And thanks for the contribution! @theospears

**Comment by theospears** [comment]
> The website displays a checkmark next to goals indicating data has been entered for that goal today. How would displaying such help you in your case?

For me this would be sufficient about 95% of the time so would definitely be a reasonable option for the list view. It wouldn’t solve eg knowing whether I have yet achieved my target daily XP in Duolingo. 

> How about being able to filter accordingly (hide goals with data today, aka show only goals without a datapoint for today)?

Personally I don’t have enough goals to need this, although I could imagine other people using it.

**Comment by theospears** [comment]
Closing this out in favor of #288
