### ISSUE TITLE
Expectations management: call it "Beeminder Companion App" or something

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#212]
@bee had a brilliant idea to manage expectations about the app: literally change the title to "Beeminder Data Entry" or "Beeminder Companion App" or something that makes it impossible for a user to be like "beeminder sounds intriguing [heads to app store] wtf this doesn't let me do anything, 1 star"

**Comment by krugerk** [comment]
There are some tips at https://developer.apple.com/app-store/product-page/ for naming the app, using the subtitle, designing captivating app previews, and so on.

**Comment by krugerk** [comment]
It looks like 'Data Entry Companion App' has been entered as part of the app title/description to accompany the 5.8 release.

here a screenshot of the app's store entry, taken on 2020-11-11:
![Beeminder App Store Page - Data Entry Companion App](https://user-images.githubusercontent.com/4656811/98818253-92cc7a80-242b-11eb-8df1-7ea95f71977c.png)
