### ISSUE TITLE
The Beehive Collective of Obtuse Nerdtastic Tools

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#213]
![image](https://user-images.githubusercontent.com/9928/95241678-f4f9e600-07c2-11eb-87f8-10f2cfb14d20.png)

Not sure if it's easier said than done or if @andrewpbrett has reasons to keep it but I wish we could change that "Maker and Baker LLC" to "The Beehive Collective of Obtuse Nerdtastic Tools".

(It's also possible we shouldn't rock the boat with Apple who may declare us in violation of godknowswhat at any moment and yank the app. ☹️ I have no idea how to gauge that risk.)

**Comment by krugerk** [comment]
Snoozing
