### ISSUE TITLE
redirects to wrong place for goal creation?

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#22]
maybe / apparently the iOS app sends to the website for goal creation but maybe doesn't send you to the right place?

> Ah, you're on the iOS app? It's not actually possible to make a goal in the app at all, so it actually sends you to the webpage, but it sends you to the wrong bit. I should pass that feedback on again in case it's been lost in the shuffle!

@nikki for more info

**Comment by krugerk** [comment]
in 5.6.4 the URL loaded in "create goal" is

```
https://www.beeminder.com/api/v1/users/_<username>_.json?access_token=_<access token>_&redirect_to_url=https://www.beeminder.com/new?ios=true
```

( aka log in user, followed by https://www.beeminder.com/new?ios=true , which one could load in the desktop browser )
which loads what appears to be the

https://www.beeminder.com/new
link with the + button (representing _Add progress manually to Beeminder (web, email, Slack, SMS, or mobile apps)_ already tapped (skipping any of the auto-sourced)



Which URL should be loaded instead?

**Comment by krugerk** [comment]
See the previous comment. This appears to be the desired location for new goals when launched from the app.
