### ISSUE TITLE
Value not fully visible in today widget on iOS 14

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#220]
```[tasklist]
### Desiderata
- [ ] Is this moot now that Today Widgets are deprecated?
```

This concerns the today widget and the appearance of a vertical bar that appeared in the widget under iOS 14.

![image](https://user-images.githubusercontent.com/4656811/96911410-1cc69a80-14a1-11eb-888f-4f8086ef7add.jpeg)

App Version: 5.8
Device Hardware: iOS device with 4" display
Device Software: iOS 14.2

## Cognata

* #68 

_**Verbata**: visual glitches, widgets,_

**Comment by krugerk** [comment]
Originally I just thought this was a blemish. However, when I actually wanted use the widget, I noticed that that little black mark (in the screenshot) is what is left of the value, which would change by tapping - and +.

**Comment by krugerk** [comment]
These today style widgets may be obsolete once the iOS 14 widgets, #68, are available in the app.

**Comment by theospears** [comment]
Today widget is deprecated. No further work will be done on on.
