### ISSUE TITLE
Datapoints entered after midnight don’t count towards correct day for certain deadlines

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#228]
```[tasklist]
### Desiderata
- [ ] Replicata
- [ ] TBD
```

Report:
> I have some goals with a deadline at 00:50 am. Whenever I enter a datapoint between midnight and this deadline, the datapoint will already be counted toward the next day (technically the current day, but the next day from the point of view of this goal - hard to explain but I hope you know what I mean). Therefore, I always have to dial the date of last-minute datapoints back by one day manually (otherwise I would derail unjustifiedly). I have not seen this happening with goals where the deadline is 3 am or 4 pm or any other time, so I am guessing it has something to do with the fact that the deadline is between midnight and 1 am.

Place where the code maybe tries to address this (HT krugerk):
https://github.com/beeminder/BeeSwift/blob/e0db275bffd9cc51694f3df28244fd9f49c2c05f/BeeSwift/TimerViewController.swift#L138

## Cognata

* #26 
* #361 
* #248 

_**Verbata**: calendar day vs beeminder day, end-of-day,_

**Comment by krugerk** [comment]
From the description I understand the user has a goal with a deadline of 00:50 or 12:50 AM. When entering a datapoint at a time between midnight and this deadline, ten before one in the morning, the app enters the data with a daystamp of the day it occurred but expected was that the datapoint would be entered with a daystamp to match the 'long night'.

**Comment by dreeves** [comment]
This is a pretty bad bug, using the calendar day instead of the Beeminder day. Another user reported it today.

**Comment by gbear605** [comment]
I just ran into a similar issue, where my goal's deadline was a 5:00 AM and then I used the app timer at 1:00AM to enter in a data point. The data point's date is set to the *current calendar date* while I wanted the data point's date to be the previous day's date so that it would stop me from derailing. Luckily I noticed, but to fix it I had to delete the data point and copy the data into a new data point.

**Comment by krugerk** [comment]
Thanks for the report, @gbear605.

Steps to reproduce seem clear.

From a quick glance, it appears the [code at least attempts to address this particular situation](https://github.com/beeminder/BeeSwift/blob/e0db275bffd9cc51694f3df28244fd9f49c2c05f/BeeSwift/TimerViewController.swift#L138).
It looks like it posts an unofficial "urtext" (^1) to the datapoint endpoint. Thus it might be not be clear if daystamp needed to be set and when not the backend takes currentDate or if urtext should have been enough but the daystamp listed there is wrong.


--
1 - urtext as a parameter is not listed https://api.beeminder.com/#postdata

**Comment by dreeves** [comment]
Report from user jellyberg the other day that sounds the same as this.
