### ISSUE TITLE
Datapoints should be editable / removable within the app

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#230]
As is, the app hides the data entry input section for autodata goals. However, unlike the website, the app allows neither editing nor removing such a datapoint.

I think that the app should allow the user these two modifications to an autodata goal's datapoints.

For the datapoints from manual goals, tapping an entry in the GoalVC opens the EditDatapointVC where the data can be modified (date, value, comment) and/or removed.

App: 5.8

**Comment by dreeves** [comment]
Good call. Beedroid has this functionality and it does feel pretty fundamental.

**Comment by adamwolf** [comment]
I do not think Beedroid lets folks delete or edit autodata datapoints,
although it does let you browse them.

**Comment by dreeves** [comment]
Oh, sorry, I missed the part about autodata! So, yeah, BeemiOS should follow Beedroid's lead on this. No editing of autodata data. We have a Beebody gissue about this and intend to sort out what the rules should be exactly for modifying autodata datapoints. In the meantime, the apps should just not allow it.

**Comment by krugerk** [comment]
Sure enough, the android app shows 'datapoint editing is not allowed for autodata goals'.

**Comment by krugerk** [comment]
- Show a similar message as in beedroid when user taps a recent datapoint
- Allow displaying yythe content (comment) in its entirety

**Comment by andrewpbrett** [comment]
Is this issue saying that autodata datapoints should be editable (as in the title and description)? Or that they should not be editable? 

In any case, the app currently does not allow editing/deleting autodata datapoints, and does allow editing/deleting non-autodata datapoints, so I'm going to close.
