### ISSUE TITLE
Log caffeine via Apple Health

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#232]
[A forum user has requested tracking caffeine via Apple Health.](https://forum.beeminder.com/t/logging-caffeine-via-apple-health/7494)

 It appears from that post that caffeine in Apple Health is tracked at the milligram level.

**Comment by claudinec** [comment]
Very belated acknowledgment and thank-you: https://forum.beeminder.com/t/claudines-journal-system-upgrade-2024/11430
