### ISSUE TITLE
Today widget still populated and allows submitting data even after logout in the app

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#236]
## The steps to reproduce the bug from scratch:

1. beeminder for ios version 5.8
2. log in via the app
3. have some goals, view the main screen (gallery / list of goals)
4. leave the app, configure today widget
5. note that the widget shows up to three goals
6. return to the app
7. settings / sign out
8. note the app now asks for login data
9. leave the app, return to the screen with the today widget
10. notice the widget still shows the goals of before
11. and allows submitting data (in case at least one of those goals allows manual data entry)

## A clear/concise description of what you expected to happen

 - no goals listed in today widget after signing out
 - instead of a blank widget, widget should show a message
  - that one is not signed in, no goals configured ... 
  - return to the app, load goals there, ...

## What actually happened instead

List of goals remained available in the widget.
Widget allowed sending data to those goals.

## Extras

 app version: 5.8
 device: iOS device with iOS 14.2

**Comment by adamwolf** [comment]
we actually have the same problem in beedroid! :)

**Comment by krugerk** [comment]
See, the apps have more in common than some of these tickets may indicate. 😛 

The today widget grabs data from storage
https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwiftToday/TodayViewController.swift#L46

which is populated app side
https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/CurrentUserManager.swift#L179

As is, signing out does not clear the goal data stored there:
https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/CurrentUserManager.swift#L146
