### ISSUE TITLE
goal not sending new data to server until user presses refresh all icon

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#24]
when I complete the goal and use the iOS app to manually log the datapoint the task appears to update and the time to the next instance is updated ie 1 or 2 days away. However the badge in the app is still showing as incomplete and I still get reminders. I just did a test to show you, however the badge item has now cleared! So this is what I'm up against, sometimes it works and sometimes it doesn't. So I unless I forget, I have to go back into the app for the second time and click the refresh icon and then all is well.

**Comment by krugerk** [comment]
marking this as a dup of #40 (closing this one and not that one because the other has more data)
