### ISSUE TITLE
Stay logged in after device restart

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#244]
```[tasklist]
### Desiderata
- [ ] Confirm replicata in modern BeemiOS
```

## Replicata

1. Log in to Beeminder app
2. Restart iPhone

## Expectata

You're still logged in.

## Resultata

You're logged out.

## Cognata

* #73 

_**Verbata**: staying logged in, not logging users out prematurely,_

**Comment by theospears** [comment]
Cannot repro with current app version
