### ISSUE TITLE
hh:mm input

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#247]
The website allows entering data in a format for times. The current (5.8) app does not. One must manually convert a time, say 10:25 to 10 + 25/60, entering 10.41666667 as the datapoint's value.

The app should provide a means for entering data as time (hh:mm) directly, similar to how the website does.

It may make sense to default to this type of input for goals with the [property hhmmformat set to true](https://api.beeminder.com/#attributes-2).

**Comment by andrewpbrett** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-01-29 at 21 19 50](https://user-images.githubusercontent.com/35588/106348041-fa9aa080-6277-11eb-899a-9b3d2d3b5b2b.png)


The keyboard has a `:` on it, I'm not sure what you're suggesting that would go further than that.

**Comment by krugerk** [comment]
Right you are! I am pretty sure I noticed then when digging into the project in the middle of past year while looking at the code.
😩 And yet I completely overlooked it recently while using the app, attempting to enter times.

What could we do instead? We could use a [datepicker](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/) in time mode, perhaps show it by default as input for `hhmmformat`ted goals and allow the user to cycle through the available input forms.

**Comment by andrewpbrett** [comment]
Adding the zzz label since the current interface is sufficient.

**Comment by krugerk** [comment]
I agree. We can close this one since as you noted and as we see, the app does accept hh:mm as input. Another ticket can be made to address the other comments.
