### ISSUE TITLE
App Icon missing padding

### ISSUE THREAD

**Issue by dsernst** [beeminder/BeeSwift#25]
The app icon could really use some white padding around the sides. 

Here's an example of what it looks like next to other common apps:

<img src="https://user-images.githubusercontent.com/6340841/72313562-97c07200-3640-11ea-849b-407b240f455c.png" width="375px" />

Just like 20% padding around the sides would make it look a lot cleaner.

**Comment by mauricioralcala** [comment]
I agree. Padding would make it look more uniform with the rest of the OS.

**Comment by andrewpbrett** [comment]
@krugerk the icon now has a thin black border around the edge, I don't think I've seen it before so I'm assuming this was introduced with the new icon sets here? https://apps.apple.com/us/app/beeminder/id551869729

**Comment by krugerk** [comment]
closing this one - app icon with more padding - and handling the black lines in a separate ticket (#179) (should allow for better issue tracking)
