### ISSUE TITLE
Make use of goals' tags

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#274]
The [goal resource now includes a list of a goal's tags](https://changelog.beeminder.com/#3691). Eventually the iOS app may want to support these.

Ideas from krugerk:
- show the tags across the goal cell in the gallery
- support grouping goals by tags
   - See [Altbee](https://altbee.aeonc.com/) for an example. Altbee allows one to create goal categories based on tags. These categories can be sorted and appear as such. It uses a fallback category containing all red goals as well as all others not included in one of the other categories (tags).
- support filtering by tags
- maybe tapping a tag can work as a quick filter to quickly filter goals with just those tags, perhaps updating the search bar accordingly
- support grouping based on combination of tags (goals may contain more than one tag)
  - support primarily AND
  - provide support though for OR, when specifying more than one tag
- widget (currently today extension) should be configurable to not care about tags, only allow goals with certain tags to be shown, prevent goals with certain tags from being shown

**Comment by dreeves** [comment]
Step 0 before we think about this one too hard will be having a reasonable interface for goal tags on the website.
