### ISSUE TITLE
Customizing badge

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#277]
Currently BeeSwift shows a badge with a number indicating the 'beemergencies', those due yet on the current day.

How about allowing users to customize this? Due today, due through tomorrow, in two days, or this week?

**Comment by dreeves** [comment]
Thanks for this idea! I think it violates [the Anti-Settings Principle](https://blog.beeminder.com/choices) though. If you disagree, could you start by articulating a use case (if you personally have one) on the forum?

**Comment by krugerk** [comment]
I might like the option to have the badge indicate
- number of goals due within the the alert window
- number of goals due within the next 
  - day (today)
  - next day (tomorrow)
  - next seven days (a week, the Akrasia horizon).

I might also like to disable it within the app (it can be disabled at iOS level).
