### ISSUE TITLE
Signup lets you fill out the form and then says j/k do that again on the website

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#279]
NICKY: "it seems that it actually lets you enter all your details and then tells you that you need to go to web and do it again. That's really rubbish as a user experience"

We're mitigating the severity somewhat by emphasizing that BeemiOS is a "data entry companion app":

![image](https://user-images.githubusercontent.com/9928/118408247-95599800-b639-11eb-9269-f67baad881a0.png)

But, as Nicky also points out, that's just a subtitle and if you just hit download you may not see it.

**Comment by krugerk** [comment]
Wow,
look at the turnaround on that one: ticket a week ago, addressed in a commit 17 hours ago

addressed here: 965de607169ddb3d847240f1b992c62d340d4e98


Nice to see some activity here!

**Comment by andrewpbrett** [comment]
closed via 965de607169ddb3d847240f1b992c62d340d4e98
