### ISSUE TITLE
Release 6.1 Manual Test Plan

### ISSUE THREAD

**Issue by theospears** [beeminder/BeeSwift#302]
To reduce total manual testing, and allow the work to be distributed if there are multiple parties interested in testing, we are going to experiment with manual testing all 6.1 changes together once there is a test flight release, rather than testing each PR individually. (Individual PRs will still receive a rough high level testing before merging.)

This issue tracks all the recommended manual testing before releasing 6.1 publicly.

## Fix all compiler warnings #301 

On a single device:
* [ ] Refresh goal while offline and check error
* [ ] Check reset password button still works and brings up web view
* [ ] End a timer session while offline and check error

On devices with and without a notch:
* [ ] Verify today widget still renders and accepts input
* [ ] Check that healthkit metric chooser looks reasonable
* [ ] Check that healthkit metric removal looks reasonable
* [ ] Check that edit data point UI looks reasonable
* [ ] Check that goal notification settings looks reasonable
* [ ] Check that gallery view looks reasonable

##  Share all UserDefaults with the app group #300 

* [ ] Log into an older version of the app, upgrade, and check we are still logged in
* [ ] Log out on new version, downgrade, and check we are logged out
* [ ] Log in on new version, downgrade, check we are still logged in
* [ ] Confirm the today widget still works

**Comment by theospears** [comment]
@dreeves now there is a 6.1 release in TestFlight could you see if there's someone from the team who could help with this list?

**Comment by gbear605** [comment]
I’ve tried to confirm for everything that I can. All were on an iPhone with a notch.

- Refresh goal while offline and check error: it displays “**Error** Could not refresh graph” in a popup that looks reasonable to me
- Check reset password button still works and brings up web view: the button (technically the text is “forgot password?”) does successfully bring up the web view
- End a timer session while offline and check error: it displays “**Error** Failed to add datapoint” in a popup that looks reasonable to me
- Verify today widget still renders and accepts input: I was **unable** to add the Beeminder widget; when I searched for it while trying to add a new widget, it did not show up. This may be related to it being the Testflight version.
- Check that edit data point UI looks reasonable: looks good to me
- Check that goal notification settings looks reasonable: the notification settings mostly look good, but it wasn’t obvious that clicking on the text that says “Start notifications at: 22:30” would let me change the setting. I initially assumed I would need to go to the website. I would recommend changing these to use normal iOS components if possible.
- Check that gallery view looks reasonable: other than the discussion on the Discord about the checkmark not being clearly attached to a goal, which we decided to punt on, the gallery looks good to me

I’m not familiar with the HealthKit setup and don’t have HealthKit goals to test with.

**Comment by alisonfarrar** [comment]
Here are the results I got. All were done on an iPhone without a notch (I think, I had to look up what this means... I have an iPhone SE).
Fix all compiler warnings https://github.com/beeminder/BeeSwift/pull/301
On a single device:
- [x] Refresh goal while offline and check error. Displays "**Error fetching goals** The internet connection appears to be offline."
- [x] Check reset password button still works and brings up web view; the "forgot password?" button brings up web view while offline.
- [x] End a timer session while offline and check error. Ending a timer session and clicking "Add datapoint" brings up an "Error: Failed to add datapoint" in a popup.

On devices with and without a notch:
- [x] Verify today widget still renders and accepts input. If this is referring to the old style widget (not the new home screen ones), this is true.
- [x] Check that healthkit metric chooser looks reasonable
- [x] Check that healthkit metric removal looks reasonable
- [x] Check that edit data point UI looks reasonable
- [x] Check that goal notification settings looks reasonable. Agree with @gbear605 that it's not obvious that the "Start notifications at: " and "Goal deadline: " text is a button. They look like plain text to me.
- [x] Check that gallery view looks reasonable. I reported an issue where only some goals with todayta are showing checkmarks.
