### ISSUE TITLE
Icon overlap at top of phone screen

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#311]
Via Faire:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/9928/191846315-82ccdc50-ddac-48a2-b538-4ad8ccfac779.png">

Note the app's settings icon overlapping the phone's battery icon and some other overlap on the left.

## Replicata 

TBD

## Expectata

Things don't overlap.

## Resultata

Things do overlap.

## Nota Nebulosa

I can get more details from Faire if this isn't replicating for others.

## Desiderata

- [ ] Fix it
- [ ] Include it in the changelog

## Cognata

* #192 
* #306 
* #294

_**Verbata**: icon overlap, menu bar, navigation bar,_

**Comment by theospears** [comment]
Thanks for reporting!
If this is in the current TestFlight build it's great to also report via the TestFlight app as that also includes lots of relevant details along with the report.

Some questions:
1) Versions: What model of device is this? What version of iOS? What version of the app?
2) Do you know what causes the circle in the top left? (I wondered if it was an on-screen replacement of a broken home button)
3) The "status" icons seem to be moved down a bit from the top of the screen. Does this happen in any other app?

**Comment by dreeves** [comment]
Faire's answers follow. She's not on TestFlight yet. 

1. iPhone 13 mini, iOS 15.6.1, Beeminder “6.0 (19)”
2. The status icons appear to be where they always are on this phone, they don't rest quite at the very very top of the screen. I suppose there could be some variation in the viewing of the screenshot on different devices, though!

**Comment by theospears** [comment]
Faire: Could you try the testflight version please? @dreeves can give you the link. I think it's _unlikely_ to fix the problem you are seeing, but some of the layout code has been reworked in that version, so let's give it a try before investigating in more detail.

**Comment by dreeves** [comment]
She confirms that the bug does not replicate in the TestFlight version! 🎉
