### ISSUE TITLE
Disconnect Semaphore from beeminder/BeeSwift repository

### ISSUE THREAD

**Issue by theospears** [beeminder/BeeSwift#322]
We now use Github Actions for running automated tests.

However, Semaphore still appears to be connected to the repository, and trying to post results. I think this is a github/semaphore configuration thing, rather than a file in the repository (I've deleted the relevant files). Could we see if we can modify the repository configuration to disable this? I don't have an appropriate level of access to do so.

**Comment by adamwolf** [comment]
I looked in the repository settings, and didn't see anything.  I'll look in the organization ones too.

**Comment by theospears** [comment]
Possibly this is linked with @andrewpbrett 's personal oauth, so only he can disconnect it?

**Comment by andrewpbrett** [comment]
I've revoked access to Semaphore 2.0, which said it had been used in the past week, so hopefully that did the trick?

**Comment by theospears** [comment]
Thanks!
