### ISSUE TITLE
Don't import last week of data for new goals (for now)

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#334]
HT Mary.

## Replicata 

1. Decide you'd like a new Apple Health autodata goal
2. Create it as a manual do-more goal, per the help docs
3. Go to BeemiOS and do the "add source" thing to point to that new goal
4. Do some jumping jacks or whatever

## Expectata

That data starts appearing above the bright red line.

## Resultata

The previous week of data is imported which would normally be great but since the goal already got created starting at zero, I'm now waaaay above the bright red line, which kinda spoils the goal unless I know about ratcheting. 

Worse, if it's a do-less goal then I insta-derail which is super broken.

## Desiderata

- [ ] Don't do the last-week import thing
- [ ] Make a new gissue for solving this a better way since importing the last week of data is nice
- [ ] Record this improvement in the changelog

## Cognata

* https://help.beeminder.com/article/61-apple-health

_**Verbata**: newbee confusion, pulling in the last week of data, importing old data, insta-derails,_

**Comment by adamwolf** [comment]
i'm pretty confused about this.  why does importing past (presumably positive numbers) data for a do-more make you derail?

**Comment by dreeves** [comment]
For a do-less you may insta-derail and for a do-more it's a lot of excess safety buffer. Kinda buggy either way and especially egregious in the do-less case.
