### ISSUE TITLE
multiple alerts about invalid credentials

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#34]

**Comment by adamwolf** [comment]
What is this? I may be seeing something like this on Beedroid...

**Comment by andrewpbrett** [comment]
I'm digging into it now but when I post to `/api/private/sign_in` and get a failure, the response block is getting called 3-4 times... I'm pretty sure I haven't changed any code in that area but maybe an underlying library changed. If you're seeing the same though that would be interesting evidence to submit for admission to the court.

**Comment by adamwolf** [comment]
Mine is something to do with me.json, so maybe not related at all.

**Comment by adamwolf** [comment]
It may be https://github.com/beeminder/beeminder/issues/1236

**Comment by andrewpbrett** [comment]
Nope it was something in the app.
