### ISSUE TITLE
Blue text doesn't work in dark mode

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#346]
```[tasklist]
### Desiderata
- [ ] Decide whether to try a quick mitigation or do something more fundamental with switching to a due-by table (see cognata)
- [ ] Do that
- [ ] Include it in the changelog
```

HT Philip

![image](https://user-images.githubusercontent.com/9928/202783392-b4b1f1e3-2d87-4ed7-bf31-5d5833ccf99a.png)

Note the "+3 +6 +10" below the graph. Those are meant to be the amounts you need in order to get into the orange, the blue, and the green -- ie, to get 1, 2, and 3 days of safety buffer.

But those can be all wrong for some goal types, I think, and we need to switch to a due-by table like Beedroid has...

## Cognata

* #209 
* #229 
* #249

_**Verbata**: delta text vs due-by table,_

**Comment by theospears** [comment]
Fixed by  #404
