### ISSUE TITLE
Deltas under graph seem wrong

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#36]
Placeholder, needs repro steps, etc, but this is from Grayson who's super clueful:

https://forum.beeminder.com/t/ios-app-graphs-show-oldest-4-out-most-recent-5-data-points/6631/6?u=dreev

**Comment by dreeves** [comment]
More from Grayson on this:

https://forum.beeminder.com/t/ios-app-graphs-show-oldest-4-out-most-recent-5-data-points/6631/8?u=dreev

**Comment by andrewpbrett** [comment]
So right now on grayson/junk-free:

```
> g = findg "grayson/junk-free"
> g.delta_text
=> "+1.18 +1.18 +1.18"
```

The deltas under the graph on the iOS app are based on what comes back from the API for `delta_text`. 

Could this actually be a beebrain/YBHP issue @dreeves @adamwolf ?

**Comment by dreeves** [comment]
Ah, yes! So `delta_text` is a crude confusing version of the dueby table and maybe clients like BeemiOS should just parse `dueby` instead. (And better yet, philosophically, I think BeemiOS should just show safesum and make it easy to get to the full dueby table if you want to know the things delta_text was telling you.) But also maybe that's important for Beeminder to keep `delta_text` correct for backwards compatibility. Namely, the amounts you need to do get 1, 2, and 3 days of safety buffer. (It was only ever a vague approximation to that pre-YBHP. Lanes delenda est!)

Aaand, dammit, `dueby` isn't actually documented in the API. Maybe it's there though, just undocumented?

So, ok, the API needs to not break that. Gissued as https://github.com/beeminder/beeminder/issues/1350 -- stand by.

**Comment by dreeves** [comment]
This should be done now!

**Comment by andrewpbrett** [comment]
Thanks! I'm going to close this then; definitely agree that it would be better to just have the dueby table in the app. Probably a larger discussion though - it might violate PDP to remove it, especially if there's not a dueby table somewhere in the app to replace it.
