### ISSUE TITLE
Get badge update when emergency day status changes on backend

### ISSUE THREAD

**Issue by adamwolf** [beeminder/BeeSwift#376]
This issue tracks an upstream issue on backend, https://github.com/beeminder/beeminder/issues/4106, which will send a silent notification to BeeSwift when a goal changes from emergency day to not, or vice versa.  This will include the current number of emergency day goals for that user, which will help keep the app badge accurate.

See:
- https://github.com/beeminder/beeminder/issues/4106

**Comment by theospears** [comment]
@adamwolf can I bump this up your priority list a bit? I think it is likely to block releasing the next beeswift version.

**Comment by theospears** [comment]
I believe the corresponding backend work is now done.
