### ISSUE TITLE
Date picker wraps around to 1 for the first of the current month

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#386]
```[tasklist]
### Desiderata
- [ ] Add the special case or whatever?
- [ ] Discuss how to totally redesign this to make it moot?
```

## Replicata 

1. Say it's May 31st and you want to enter data for tomorrow
2. So you hit the "+" on the "31" and it wraps around to "1"
3. So far so good, seemingly
4. Submit the datapoint

## Expectata

A datapoint added for June 1st.

## Resultata

A datapoint added for May 1st!

If this is a do-less goal, this can even derail you.

(Pretty bad for a typical cumulative do-more goal as well since your data will just be all wrong but you won't notice since it will just bump up your current value like normal even though you technical added the datapoint a month in the past.)

_**Verbata**: anti-magic, date wrapping, datepicker, date-picking, specifying datapoint date as day-of-month,_

**Comment by dreeves** [comment]
Beedroid handles this by showing both month and day when it's ambiguous.

**Comment by theospears** [comment]
Could you attach a screenshot of the relevant case in beedroid?

**Comment by dreeves** [comment]
![image](https://github.com/beeminder/BeeSwift/assets/9928/e83ad012-6cbe-4129-9e4b-781a1e551145)
