### ISSUE TITLE
Refreshing a goal in the app should refresh autodata

### ISSUE THREAD

**Issue by theospears** [beeminder/BeeSwift#392]
## Replicata 

1. Go to a goal page in the app
2. Pull down to refresh the goal

## Expectata
Beeminder re-fetches any autodata, and then shows the new results

## Resultata
New data is fetched from the server, but autodata is not refreshed

## Nota Nebulosa

This was accidentally broken by #352

## Cognata

* #352 (regression introduced)

_**Verbata**: autodata syncing, force-syncing,_

**Comment by theospears** [comment]
This was fixed a while ago.

**Comment by krugerk** [comment]
> This was fixed a while ago.

Possibly in #446
