### ISSUE TITLE
Unsubmitted datapoint value changes when leaving and coming back to the app

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#417]
```[tasklist]
### Desiderata
- [ ] Replicata or just confirm what Justin experienced is true for everyone
- [ ] Make a guess as to hard this is dev-wise
- [x] Theo just fixes it (part of v6.6)
- [x] Tweet the UVI on 2024-04-02
```

Message from Justin Hong in support from 2023-09-02 with details and even video proof!

First let's see if we can replicate this easily ourselves by typing a value for a datapoint, then swapping back and forth to another app before coming back to submit the datapoint.

## Cognata

* https://secure.helpscout.net/conversation/2349608296/162520?folderId=2972058 (internal link)
* #442 (PR FOR THIS)
* http://beeminder.com/changelog#4825 (THIS UVI)

_**Verbata**: not losing what the user typed,_

**Comment by theospears** [comment]
I believe this was fixed by #442.
