### ISSUE TITLE
Graph images flicker on gallery screen

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#43]
## Reseminata 

From the gallery screen, go into a goal, and then back to the gallery screen. 
Or, alternatively, pull to refresh your goals

## Expectata

Only graphs that have changed should update

## Resultata

Every single graph briefly flickers the placeholder bee image.

**Comment by krugerk** [comment]
This happens because as is, the goals are fetched each time the goal gallery is viewed. 

I am working on this.

**Comment by krugerk** [comment]
The screenshots in the google play store for the android Beeminder app show an option for setting the interval at which the app will check for updated graphs.
It not clear to me how up-to-date those images are.
Nonetheless, is such a setting along a direction in which this app should be headed?

**Comment by dreeves** [comment]
Negative, the plan is to remove that setting from Beedroid. [Anti-Settings Principle](http://doc.bmndr.com/choices)!
