### ISSUE TITLE
Inaccurate Mindful Minutes

### ISSUE THREAD

**Issue by sachiesaaan** [beeminder/BeeSwift#452]
## Replicata 

1. Open Health app integration
2. Add Mindful Minutes as source
3. Add Data to Apple Health
4. Check Data on Beeminder

## Expectata

data as itself

2min →　2min

## Resultata

every data is counted as +1

ex) 2min →3min,  10min →11min

ex2) If I added 2min and 1min in a day, it is counted as 2+1 min + 1+1min = 5min

## Nota Nebulosa

![IMG_4273](https://github.com/beeminder/BeeSwift/assets/40904182/035c4c99-1006-4517-8bea-7304cc84bbfa)
![IMG_4274](https://github.com/beeminder/BeeSwift/assets/40904182/94e07450-60c3-4866-a453-30e9f85309ec)

_**Verbata**: no need, to add, keywords, when, first creating, a gissue,_

**Comment by theospears** [comment]
Thanks for the thorough bug report!

The current beeminder algorithm for this metric is:
`
+1 minute for every wall clock minute contained within a meditation session
`
So e.g. a session from 6:00:30 - 6:01:15 will count as 2 min. Note this is _slightly_ different to the reported behavior - e.g. a session which is 6:00:05 - 6:00:55 will be reported correctly.

The Apple Health algorithm appears to be
`
Calculate the total duration of all meditation sessions, without double-counting overlap, and round to the nearest minute, with 30s rounding up
`
So e.g. a pair of sessions 6:00:03 - 6:00:23 (20s) and 6:00:01 - 6:00:21 (20s) will total 22 seconds, and round to 0 minutes.

For Beeminder we could either switch to exactly matching the apple algorithm, or leave out the rounding so we can report non-integer numbers of minutes. Curious if people have thoughts on which is better.

**Comment by sachiesaaan** [comment]
Thank you for fixing this! Personally, I do sessions for some minutes and never care about seconds so rounding to the nearest minute is fine..
