### ISSUE TITLE
Pull-to-refresh is much harder to pull than, for example, the Mail app

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#48]
HT Richard Moulange (reply to annoyingness straw poll):

> The most annoying thing at the moment is that if I start with my thumb about halfway up the screen and pull down fairly slowly on the Goals tab, the ring of tick marks at the top that indicates the refresh process does not complete (i.e. not all 12 rings appear). Please would you make it so slightly less thumb speed or distance is required to refresh?

**Comment by andrewpbrett** [comment]
It's using the system/standard `UIRefreshControl` but I do agree that it feels harder than other apps.

**Comment by krugerk** [comment]
In my subjective experience, if I start the pull toward the top of the list, refresh kicks in before my thumb arrives at the middle of the 4” device.  This works consistently and is easy enough for me to manage.
If however the touch gesture starts lower, say toward the middle, then I do not always manage to cause a refresh before having to lift my thumb.

Unlike others’ comments, it seems to me this is more or less the same for Beeminder as it is for Mail.

**Comment by krugerk** [comment]
Feel free to reopen should it seem necessary. 

I myself did not notice anything more difficult with pull-to-refresh on a few iOS devices of various screen sizes. They were all running recent iOS versions at the time (14.x).

**Comment by krugerk** [comment]
See #84, a ticket concerning supporting pull-to-refresh on the goal view.
