### ISSUE TITLE
Not getting notifications

### ISSUE THREAD

**Issue by chipmanaged** [beeminder/BeeSwift#51]
Fairly regularly, I don't get notifications on goals that then derail. (I'm on the TestFlight version 5.6.4) I derailed at 9:31 pm last night without getting any notifications leading up to that and again this morning at 9:46 am without getting any notifications.

- iPhone XR
- My notifications are on, both in the app and in iOS settings.
- I'm opening the app throughout the day, though I'm not sure at precisely what intervals. I'd expect we can count on it being roughly in the ballpark of any average user, though.
- I'm not actually sure whether I've received any notifications since updating to 5.6.4. I'll keep an eye out for the first one and will report back when I get one.

**Comment by chipmanaged** [comment]
Still no notifications today, so I'm turning on email notifications to make sure that they're supposed to be coming and that I'm not just between zenos.

**Comment by chipmanaged** [comment]
Oh, I forgot that I'd had some Slack notifications turned on and so I should have gotten at least these. Can now confirm that I'm definitely getting 0 beemios notifications:

![Screen Shot 2020-05-15 at 2 39 07 PM](https://user-images.githubusercontent.com/10947385/82084814-eb5bce80-96b9-11ea-8e50-a386b358c8f9.png)

**Comment by chipmanaged** [comment]
Hmm... I was going to try turning notifications off and then on again, since this version turns them on for me when I say yes to the popup, but I... I can't find where to turn them off unless I turn them off individually. Am I an idiot? (Maybe just keep the scope of the answer to that question to the boundaries of this gissue.)

**Comment by andrewpbrett** [comment]
@chipmanaged I'm going to close this since it appears to be fixed in the latest TestFlight build, but feel free to reopen if you're still seeing it.
