### ISSUE TITLE
Can't make keyboard go away after using the search button

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#53]
From Roman Duda

Minor bug report related to the search bar on iOS on iPhone, I can’t find any way to hide the on screen keyboard on the goals page after I’ve tapped on the search icon:

## Reseminata

1. Tap the search icon in the top left.
2. Search for an existing goal
3. Tap on a goal that comes up
4. Tap on back to goals in the top left
5. Now try to hide the on screen keyboard -- Tap the “x” in the text input bar 
6. Scroll down your list of goals, then scroll back up again.

## Expectata

The on screen keyboard disappears. (I *think* this is the way must other iPhone apps let you hide the on screen keyboard.)

## Resultata

The on screen keyboard stays shown. 

The only way I’ve found to hide the onscreen keyboard on the goals page is to close the Beeminder app in the iOS app switcher and the open the app again - I.e. “restart” the app.

I haven’t found an element I can tap on which moves the focus out of the input text box, which I would expect to hide the on screen keyboard.

**Comment by krugerk** [comment]
7. tap the magnifying glass. This hides the searchbar/entry area and consequently hide the soft keyboard.

**Comment by krugerk** [comment]
or we can also use the standard cancel button on the searchBar
