### ISSUE TITLE
Use WKWebView

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#54]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Beeminder" 5.6.4 (3). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by dreeves** [comment]
@andrewpbrett, sounds like this was infrastructure, not user-visible?

**Comment by andrewpbrett** [comment]
Yes, no one should notice anything different, though if it hadn't happened we wouldn't have been able to update the app starting later this year. Still, I wouldn't call it a UVI.
