### ISSUE TITLE
Red/Green/Blue text on white/black background is hard to read

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#55]
```[tasklist]
### Desiderata
- [ ] Theo's been tweaking colors; maybe this is good now?
- [ ] Screenshots of the problem if there is one
- [ ] Look up Apple's HIG for colors?
```

_**Verbata**: colors, contrast, accessibility, a11y,_

**Comment by krugerk** [comment]
# red
## on white
 * https://webaim.org/resources/contrastchecker/?fcolor=FF0000&bcolor=FFFFFF
 * contrast ratio: 3.99:1
 * results: 3 failures, 2 pass

### example red on white
<img width="151" alt="red on white" src="https://user-images.githubusercontent.com/4656811/89583935-7ffa4680-d83b-11ea-9863-2a0ceb4822ad.png">

## on black
 * https://webaim.org/resources/contrastchecker/?fcolor=FF0000&bcolor=000000
 * contrast ratio: 5.25:1
 * results: 1 failure, 4 pass

### example red on black
<img width="151" alt="red on black" src="https://user-images.githubusercontent.com/4656811/89584690-c308e980-d83c-11ea-944e-9bdac526383b.png">

## on beeGray
 * _lastUpdatedLabel_
 * https://webaim.org/resources/contrastchecker/?fcolor=FF0000&bcolor=B2B2B2
 * contrast ratio: 1.88:1
 * results: 5 failures, 0 pass

### example red on gray
<img width="151" alt="red on gray" src="https://user-images.githubusercontent.com/4656811/89584065-b5069900-d83b-11ea-92da-e0e7f1f2e1e9.png">



# orange
## on white
 * https://webaim.org/resources/contrastchecker/?fcolor=FF7F00&bcolor=FFFFFF
 * contrast ratio: 2.53:1
 * results: 5 failures, 0 pass
### example orange on white
<img width="151" alt="orange on white" src="https://user-images.githubusercontent.com/4656811/89584312-2a726980-d83c-11ea-96cd-2486c9df686d.png">


## on black
 * https://webaim.org/resources/contrastchecker/?fcolor=FF7F00&bcolor=000000
 * contrast ratio: 8.28:1
 * results: 0 failures, 5 pass

### example orange on black
<img width="151" alt="orange on black" src="https://user-images.githubusercontent.com/4656811/89584672-bbe1db80-d83c-11ea-8a29-6a0729d80038.png">


# blue
## on white
 * https://webaim.org/resources/contrastchecker/?fcolor=0000FF&bcolor=FFFFFF
 * contrast ratio: 8.59.1
 * results: 0 failures, 5 pass

### example blue on white
<img width="151" alt="blue on white" src="https://user-images.githubusercontent.com/4656811/89584437-5d1c6200-d83c-11ea-9db9-b88af06432f5.png">


## on black
 * https://webaim.org/resources/contrastchecker/?fcolor=0000FF&bcolor=000000
 * contrast ratio: 2.44:1
 * results: 5 failures, 0 pass

### example blue on black
<img width="151" alt="blue on black" src="https://user-images.githubusercontent.com/4656811/89584651-b5ebfa80-d83c-11ea-9686-076e3e0c294a.png">


# beeGreenColor
## on white
 * https://webaim.org/resources/contrastchecker/?fcolor=51AE51&bcolor=FFFFFF
 * contrast ratio: 2.79:1
 * results: 5 failures, 0 pass

### example green on white
<img width="151" alt="green on white" src="https://user-images.githubusercontent.com/4656811/89584391-4d048280-d83c-11ea-9d8e-804746eff02b.png">

## on black
 * https://webaim.org/resources/contrastchecker/?fcolor=51AE51&bcolor=000000
 * contrast ratio: 7.52:1
 * results: 0 failures, 5 pass

### example green on black
<img width="151" alt="green on black" src="https://user-images.githubusercontent.com/4656811/89584643-b1bfdd00-d83c-11ea-8afa-571e81263c84.png">


# black
## on beeGray
 * _lastUpdatedLabel_
 * https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=B2B2B2
 * contrast ratio: 9.9:1
 * results: 0 failure, 5 pass

### example black on gray
<img width="151" alt="black on gray" src="https://user-images.githubusercontent.com/4656811/89584357-3e1dd000-d83c-11ea-9148-e7c8ec0ca3ef.png">


Take them though with a grain of salt - results expect large fonts at 14pt **and** bold

**Comment by krugerk** [comment]
![Current color palette](https://user-images.githubusercontent.com/4656811/89773474-414ae180-db04-11ea-9ec6-978d263af256.jpeg)

**Comment by theospears** [comment]
Colors have been changed since this was opened. Going to close out, but feel free to re-open or open new issues for specific instances.
