### ISSUE TITLE
All goal deltas appear to be missing when opening up individual goal pages.

### ISSUE THREAD

**Issue by emeraldfleur** [beeminder/BeeSwift#559]
# Environment 

iOS 18.2
Beeminder iOS app version 6.7 (54)
iPhone 13 Pro

# Replicata

1. From the home screen of iOS [while logged into Beeminder iOS app to an account with at least one active goal] --  tap the icon to open the Beeminder iOS app --> Goals Page
2. Goals Page --> Goal
3. Arrive at [Actual] Resultata

# Expectata [Result]

Expectata taken from first App Store demonstration image - goal deltas are present.

![image](https://github.com/user-attachments/assets/9c3ecdc8-ae8f-46ad-9ad0-9860c39afba7)

# [Actual] Resultata

No goal deltas are present.

![image](https://github.com/user-attachments/assets/602fd252-c163-4df4-b202-8b070ed98947)

**Comment by krugerk** [comment]
This was removed on purpose between 6.6 and [6.7](https://github.com/beeminder/BeeSwift/releases/tag/6.7). 

> Remove the "delta text" UI section (#455)

I agree it was a mega useful feature of the app.

#547 and/or #548 would resurrect the feature using 'due by table' in place of 'delta text'.

**Comment by krugerk** [comment]
Thanks for the report!

**Comment by krugerk** [comment]
I would say we could make a GH issue for the discrepancy between the app and the feature shown in the pics in the store. The latter shows a feature the app no longer has.

**Comment by krugerk** [comment]
Two other users have recently reported this missing feature:

https://forum.beeminder.com/t/ios-app-no-longer-shows-delta-for-safe-goals/12111

https://forum.beeminder.com/t/ios-app-no-longer-shows-delta-for-safe-goals/12111/2

**Comment by krugerk** [comment]
Yes another user has reported this missing: https://forum.beeminder.com/t/ios-app-no-longer-shows-delta-for-safe-goals/12111/3
