### ISSUE TITLE
Upgrading app to Swift 4

### ISSUE THREAD

**Issue by mrat** [beeminder/BeeSwift#6]
The app doesnt open in XCode 10, since it has to be upgraded to Swift 4.  I'd be happy to tackle this if that would be helpful and you'd be likely to accept the PR?

**Comment by andrewpbrett** [comment]
I believe that this was fixed somewhere in https://github.com/beeminder/BeeSwift/commit/dc19f5364f899d56ba401709e834c5a2e23ccc66 - in any case, I'm on XCode 10 and it'll open. Closing for now (at least until Swift 5 comes around).
