### ISSUE TITLE
use storyboard for launchscreen

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#66]
> Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen." - https://developer.apple.com/news/?id=03262020b

Currently the project is using a [xib file](https://github.com/beeminder/BeeSwift/blob/5b5af5b1369b8c7c0da7c5ff1543eec27e6e5951/BeeSwift/Base.lproj/LaunchScreen.xib) for its launch screen.

The launch screen xib should be replaced with a storyboard.

**Comment by andrewpbrett** [comment]
Fixed by #83
