### ISSUE TITLE
Twitter login should work

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#67]
should be able to log in with twitter

twitter button not available

**Comment by krugerk** [comment]
I see you are already at it (Commit e7ace8fc9cc9). From the looks of it, twitter login was removed as part of Commit f4119b9baeb51ae0 (which became [Version 5.6.3](https://github.com/beeminder/BeeSwift/releases/tag/5.6.3)) and done cleanly so restoring it might be as easy as `git revert f4119b9baeb51ae0`.

**Comment by chipmanaged** [comment]
I’ve created a twitter login.
It crashed on me right away, I’m afraid, but I’d only just added the access, so I restarted my phone.
After restarting, it gave me Twitter's "authorize" window and then came back to Beeminder but not signed in, and now the “Log in with Twitter” button is grey and doesn’t let me click it.

**Comment by chipmanaged** [comment]
Crashing Beeminder makes the "Log in with Twitter" button blue again, but takes me through the same loop. I authorize, it brings me back to the Beeminder app still logged out and with the "Log in with Twitter" button grey.

**Comment by krugerk** [comment]
The app is still [making use of the TwitterKit SDK](https://github.com/beeminder/BeeSwift/blob/59ed4813cd4f0f4820140dc4cab83b3a4466261b/Podfile.lock#L28), which [Twitter stopped supporting in October 2018](https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html).
Perhaps we could be looking at migrating to [Twitter OAuth 1.0a or OAuth 2.0 Bearer Token](https://developer.twitter.com/en/docs/basics/authentication/overview).

**Comment by krugerk** [comment]
@chipmanaged 
Are you running it locally? Are using the testflight version?

There is [a note from the older objc version](https://github.com/beeminder/beemios/blob/962fb49f7c29851644d3f4037423f70c494286e6/Readme.md#notes) suggesting that neither the Twitter nor the Facebook login buttons are expected to work locally.

> Notes
> The Twitter/Facebook buttons won't work on your local install (we couldn't figure out a way to do so without publishing secret keys). Log in with your Beeminder email/username and password.

**Comment by chipmanaged** [comment]
Both Philip and I are on the TestFlight version. (It's possible Andy has already explained that to me and that it got deleted during my mind's hourly "random information deletion" event.)

**Comment by krugerk** [comment]
OK. My understanding is that if you had build it locally without adjusting for twitter/facebook (using your own api key, for example), the logins would not work. 
But using the TestFlight version, as you indicated you are doing, then the issue is another.

**Comment by andrewpbrett** [comment]
I'm able to log in with Twitter using the latest code (0229b7fdab5a8f18cd26aad63019b2362feeec06); however, others are still not. The hope with plugging it back in and still using TwitterKit was that it would still work (and be the least effort solution); even though it's deprecated, there's nothing that they've explicitly said will stop working about it. But moving to the Bearer Token might be our best bet now.

**Comment by chipmanaged** [comment]
What would be the time commitment for doing that? (If Twitter is the only
login we offer on beemios and it's going to take a chunk of time, it could
be worth taking some time to consider whether we want to do that just now.)

**Comment by andrewpbrett** [comment]
Moving to the bearer token could be a fairly large chunk of time; we do also offer Facebook login on the app, though. I think we could probably figure out how many people are actually using non-password logins via the app and help that inform the decision as well.
