### ISSUE TITLE
allow browsing featured goals

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#70]
I was thinking it might ber nice to allow the user to browse featured goals even when not logged into the app. A minimal viable product of this might just be using the SafariVC to open the link at featured.

If the Beeminder API provides access to featured goals, a second iteration of this feature could be then to use that to display the featured goals natively.

**Comment by krugerk** [comment]
As far as I can tell, there is no API endpoint available for obtaining the featured goals.
So a solution might be just to offer a lint to the featured goals, presenting them in the safariVC or WKWebView.

**Comment by andrewpbrett** [comment]
I'd say this is outside the scope of what we want the app to focus on, at least for the near future. It should be a way for people to view their goals' status and easily add data, but most other functionality (adjusting the road, for example) should be left to the website.
