### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#73]
[Try to include a use case maybe. And delete this boilerplate.]

**Comment by krugerk** [comment]
The website also allows for sign in with google and github. Shall we support those as well?

**Comment by andrewpbrett** [comment]
We previously had google sign in on the app and literally no one used it, so neither of those are a priority right now.

**Comment by krugerk** [comment]
As far as I can tell, because the app already offers 'Sign in with 3rd party/social media', starting June 30 offering Sign In with Apple ID is required.


 > "Apps that use a third-party or social login service to set up or authenticate the user’s primary account with the app must also offer Sign in with Apple as an equivalent option."
> - https://developer.apple.com/sign-in-with-apple/get-started/

**Comment by shanaqui** [comment]
From my work elsewhere, this is correct. The BeemiOS app will be disabled (once they notice) if we don't add Apple sign-in. They are very picky about it and will demand the icon be exactly correct and function in the way they dictate, and they are looking very carefully at it.

I should add although that removing all trace of the social log-ins would presumably also be fine, we get user confusion about lack of specific social login options on the apps already.
