### ISSUE TITLE
Number of workouts as a Healthkit metric

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#74]
[Try to include a use case maybe. And delete this boilerplate.]

PS: I think we can call this a dup of #338

**Comment by krugerk** [comment]
As recent as five months ago , this has been requested again via a comment on a blog post: https://blog.beeminder.com/apple/


> Avatar
yas
3 years ago
Hi! Would it be possible to add Workouts as a data entry? I have found Exercise Minutes not be a reliable measure of runs and workouts as it often picks up walks as exercise time. Thanks.
1 
Reply
−
Avatar
yas  yas
5 months ago
Hi, any update/plans on adding Workouts to Apple Health Integrations?
Thanks!
