### ISSUE TITLE
remove magicalrecord

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#79]
[From the looks of it](https://github.com/beeminder/BeeSwift/blob/67aabb33c454cee5d9a170da124f36b82a81cbfc/Podfile#L10), the app is not making use of its declared dependency MagicalRecord. According to [MagicalRecord](https://github.com/magicalpanda/MagicalRecord), development ceased as of Version 2.4.0 (beeswift pulls in Version 2.3.2) and has been replaced by Core Data itself.

Verify that it is not needed and remove the dependency.

**Comment by andrewpbrett** [comment]
fixed by #80
