### ISSUE TITLE
Zenos don't distinguish imminent goal end date

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#8]
https://twitter.com/akajb84/status/1079808842043514880

**Comment by adamwolf** [comment]
This may be a Beeminder-wide thing, actually.  For instance, ending goals
also show up as in emergency.

**Comment by krugerk** [comment]
The iOS app shows notifications of alerts and beemergencies (due today) upon receiving remote messages (push) from the backend.

If this is an issue, then it seems to be server-side, as mentioned in the previous comment.
