### ISSUE TITLE
health app integration VC cleanup

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#85]
Here are some notes on some cleanup action ideas for the screen. The health app integration screen displays what appears to be a list, starting with a switch for sync health data reminders, followed by the goals and their associated data source. The goals belong to any of three categories: auto-sourced, manually sourced, and health integration sourced. "Add source..." appears next to the goals currently manually sourced. Ones that are auto-sourced display the source greyed out. And those with a health integration display the health metric.

### Sorting of Goals

**Actual:**
Goals are sorted in reverse alphabetical order by slug. 
**Expected:**
There is no option to adjust how they are sorted on this screen. I would think sorting them A-Z would be preferred over the reverse, Z-A.

**Actual:**
Goals are sorted in reverse alphabetical order by slug. 
**Expected:**
Allow sorting the goals on this page, perhaps on-the-fly, or by using the order specified in the app preference for sorting goals (set in settings; used by the gallery)

### Use Sections
**Actual:**
Goals of the three categories are intermixed.
**Expected:**
Display section headers and split the goals into categories by type of source. The ones that cannot be edited in the app can appear toward the button, those where currently "Add source..." is displayed can either be in the first or second section. Using sections it can be made more clear which ones are sourced via apple health metric and can be changed in the app.

### pull-to-refresh
**Actual:**
There is no way to refresh the screen (no refresh button, no pull-to-refresh). refreshed by returning to the health app integration screen
**Expected:**
pull-to-refresh is supported

### cell reuse bug
**Actual:**
The greyed out source applies to wrong goals (example apple health sourced ones) upon scrolling the list
**Expected:**
The coloring is correct even after scrolling.

### greyed out
**Actual:**
The goal is not greyed out but the source is for those auto-sourced elsewhere.
**Expected:**
Both the goal and the source should be greyed out to indicate more clearly the item is not editable.

### which goal
**Actual:**
After tapping "Add source..." one is presented with "Choose metric" and a list of metrics, but no longer sees for which goal (obviously the one we tapped, but which was that again?)
**Expected:**
The screen for picking the metric could indicate for which goal. Another option might be to use a UIPickerView.

### sorting of metrics
(This applies to the list of metrics and not the health app integration screen itself.)
**Actual:**
Some of the items appear grouped together but it is not obvious how they are sorted.
**Expected:**
At a minimum, sort the health kit metrics alphabetically.

**Comment by krugerk** [comment]
I have a branch started where I address several of these. Let the ticket be for discussion in case there are preferences about how things should be handled. They can be addressed before the merge request lands.

**Comment by andrewpbrett** [comment]
Thanks for opening this, I think just about everything I read would be a definite improvement. For sorting/grouping goals, I like the idea of having a separate section for goals that are already linked to Apple Health (and therefore can't be linked again, only delinked) and a another separate section for goals that get their data from a different integration (and therefore also can't be linked). Within each section A-Z sorting makes sense.
