### ISSUE TITLE
create goal button when no goals

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#86]
When 0 goals are loaded (user account apparently does not have any goals yet), the following is displayed in the gallery:

![no goals - in-app goal creation coming soon - visit beeminder to create a goal](https://user-images.githubusercontent.com/4656811/86533278-5793cb00-bed0-11ea-91c7-6aba420251fd.png)

Meanwhile, once at least one goal can be loaded, a cell appears in the list of goals with a button for initiating creating a new goal. This action loads the beeminder website (in-app goal creation is not supported).

I think the 'create goal' button can be removed from the list of goals so long as some exist. Perhaps a + button can appear next to the settings button in the navbar.
And it might be nice for the 'create goal' button to make its appearance in one form or another in the case the account is without goals. It could replace or supplement the message about in-app goal creation.

![Simulator Screen Shot - iPhone 11 Pro - 2020-07-05 at 14 51 10](https://user-images.githubusercontent.com/4656811/86533288-709c7c00-bed0-11ea-9525-ceff02729110.png)

**Comment by andrewpbrett** [comment]
We actually did the opposite on purpose, with the following reasoning: the app is primarily intended to be a companion to the website, and we want to encourage, if at all possible, people to have their first experience with Beeminder on a larger screen on a desktop. There's still a lot of education that's necessary for a person to have a good first experience with Beeminder that the app doesn't provide on its own. Once they've created at least one goal, we can trust them a little more (and more reasonably hope that they'll put up with some jankiness). 

So I'm going to close, but feel free to add more thoughts.
