### ISSUE TITLE
require httpS connections

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#91]
I see [insecure loads (http) are allowed to beeminder.com](https://github.com/beeminder/BeeSwift/blob/d7c68722282f114f5394900576436d50ea16875e/BeeSwift/Info.plist#L105). Surely the httpS server settings and certificate settings have been updated/upgraded within the past three years and the settings can be tweaked to stay with the times.

[SSL Server Test at ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=www.beeminder.com)

Given the app now only supports iOS 10 and later, ... I suspect the ATS exceptions for beeminder are not necessary. (Would guess the same for the other non-local ones mentioned - _akamaihd.net_, _facebook.com_, and _fbcdn.net_.)

**Comment by adamwolf** [comment]
If the defaults don't work for Beeminder, feel free to @ me and let me know what errors you get, and I could take a look on the server side!
