### ISSUE TITLE
Entering app from widget does not always take you to that goal's screen

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#97]
```[tasklist]
### Desiderata
- [ ] Is this still relevant? Is the Today widget still a thing?
- [ ] Do the replicata still replicate?
- [ ] TBD
```

## Replicata from krugerk

1. Be on version 5.6.4 or later?
2. Log in
3. Configure the Beeminder Today widget (add the widget to the Today screen)
4. Force-close the app
5. View the Today widget, tap a goal

## Expectata

To see the goal screen for the goal you tapped.

## Resultata

App opens, displays gallery.

## Nota Nebulosa

Tapping/selecting a row in the Today widget results in [a beeminder:// URL being created](https://github.com/beeminder/BeeSwift/blob/fcc79a30b8655ceb9ce66dde21d7c7cd3eef08b5/BeeSwiftToday/TodayViewController.swift#L66). The App is registered to process this and this much works -- the app starts. 

It could be a timing issue in that the app sends the "open goal" request before the goals have been loaded from the backend/server.

## Cognata

* #41 

_**Verbata**: today widget, user's intended destination,_

**Comment by krugerk** [comment]
Only partially related to #41 in that there is currently no code for #41 attempting to open the goal from a remote notification.

**Comment by theospears** [comment]
Today widgets are deprecated, and won't get any additions or fixes. As/when new style widgets are built we can work on this.
