### ISSUE TITLE
Today Widget goals not updated after entering data via Today Widget

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#98]
```[tasklist]
### Desiderata
- [ ] Confirm replicata for version 6.5 of the app
- [ ] Discuss whether this is actually bad (not obvious to dreev that it is!)
- [ ] TBD
```

Currently the widget displays at most one goal.

## Replicata

1. Enter data via the widget such that that goal is no longer the most urgent
2. Goal is updated, this works.

## Expectata

That the new most urgent goal is shown in the widget

## Resultata

The goal we just added data to is still the one listed.

## Workaround

Open the app, fetch the goals, return to the Today Widget.

_**Verbata**: staleness, freshness, syncing with the server,_

**Comment by krugerk** [comment]
5.7 (2)

The graph for the goal is updated but the description of the amount due is not.

'Add data' in today cell requests a new graph, which is displayed once it is fetched. This part works correctly.

In fact, if the widget is removed from the today screen then added again - without opening the beeminder app directly, the today widget shows old data.

**Comment by krugerk** [comment]
Right now (5.7) the widget relies on the main app for its data. The today widget can submit new data but that new data will not be reflected in the today widget until the main app has become aware of the new data and subsequently updated the data used for the today widget.

**Comment by theospears** [comment]
Today widgets are deprecated, and will see no further development
